services:
  postgres:
    image: postgres:18-alpine
    container_name: gac_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gac
      POSTGRES_USER: gac
      POSTGRES_PASSWORD: gac
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
